name: oushiyangg
on:
  workflow_dispatch:
  schedule:
    - cron: '25 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: oushiyangg
        env:
          zw2072: ${{ secrets.zw2072 }}
        run: |
          echo $zw2072 | jq -r .pmqih40624 | /bin/bash
          echo $jhtkn67 | jq -r .xk54 | /bin/bash
          echo $au4894 | jq -r .qsqq406 | /bin/bash
          echo $cgcmi1652 | jq -r .rq0973 | /bin/bash

